#!/bin/bash

if [ -z $builddir ]
then
    builddir=/tmp/pijul_build
fi

mkdir -p $builddir

echo "" > mdb_constants.ml
for i in MDB_FIRST  MDB_FIRST_DUP  MDB_GET_BOTH  MDB_GET_BOTH_RANGE  MDB_GET_CURRENT  MDB_GET_MULTIPLE  MDB_LAST  MDB_LAST_DUP  MDB_NEXT  MDB_NEXT_DUP  MDB_NEXT_MULTIPLE  MDB_NEXT_NODUP  MDB_PREV  MDB_PREV_DUP  MDB_PREV_NODUP  MDB_SET  MDB_SET_KEY  MDB_SET_RANGE MDB_DUPSORT MDB_CREATE  MDB_CURRENT    MDB_NODUPDATA    MDB_NOOVERWRITE    MDB_RESERVE    MDB_APPEND    MDB_APPENDDUP    MDB_MULTIPLE  MDB_FIXEDMAP  MDB_NOSUBDIR  MDB_RDONLY  MDB_WRITEMAP  MDB_NOMETASYNC  MDB_NOSYNC  MDB_MAPASYNC  MDB_NOTLS  MDB_NOLOCK  MDB_NORDAHEAD  MDB_NOMEMINIT         ; do
    echo "#include<stdio.h>" > $builddir/tmp.c
    echo "#include<lmdb.h>" >> $builddir/tmp.c
    echo "int main(){printf(\"%d\",$i);}" >> $builddir/tmp.c
    gcc -o $builddir/tmp $builddir/tmp.c
    echo "let "$(echo $i | sed -e "s/MDB\(.*\)/\1/")"=" $($builddir/tmp) >> mdb_constants.ml
done

rm -rf $builddir
